// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pdf.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage/annotations.dart';
import 'storage/documents.dart';
import 'storage/folders.dart';
import 'storage/tags.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -991283304;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiStorageAddTagToDocument({
    required String docId,
    required String tagId,
  });

  Future<void> crateApiPdfCloseDocument({required String docId});

  Future<String> crateApiStorageCreateAnnotation({
    required AnnotationRecord annotation,
  });

  Future<String> crateApiStorageCreateAnnotationAutoId({
    required String documentId,
    required int pageIndex,
    required String annotationType,
    required bool isStandard,
    required String colorHex,
    int? startCharIndex,
    int? endCharIndex,
    String? selectedText,
    String? rectsJson,
    String? strokesJson,
    String? noteContent,
    String? noteRectJson,
  });

  Future<String> crateApiStorageCreateFolder({
    required String name,
    String? parentId,
  });

  Future<String> crateApiStorageCreateTag({
    required String name,
    String? parentId,
    String? colorHex,
  });

  Future<void> crateApiStorageDeleteAnnotation({required String id});

  Future<void> crateApiStorageDeleteAnnotationsForDocument({
    required String documentId,
  });

  Future<void> crateApiStorageDeleteDocument({required String id});

  Future<void> crateApiStorageDeleteFolder({
    required String id,
    required bool deleteDocuments,
  });

  Future<void> crateApiStorageDeleteTag({required String id});

  Future<void> crateApiPdfExportPdfWithAnnotations({
    required String sourcePath,
    required String outputPath,
    required List<AnnotationRecord> annotations,
  });

  Future<List<AnnotationRecord>> crateApiStorageGetAnnotations({
    required String documentId,
  });

  Future<List<AnnotationRecord>> crateApiStorageGetAnnotationsForPage({
    required String documentId,
    required int pageIndex,
  });

  Future<List<DocumentInfo>> crateApiStorageGetDocuments({
    String? folderId,
    String? tagId,
    String? searchQuery,
    required String sortBy,
  });

  Future<FolderNode> crateApiStorageGetFolderTree();

  Future<List<CharInfo>> crateApiPdfGetPageChars({
    required String docId,
    required int pageIndex,
  });

  Future<int> crateApiPdfGetPageCount({required String docId});

  Future<(double, double)> crateApiPdfGetPageSize({
    required String docId,
    required int pageIndex,
  });

  Future<TagNode> crateApiStorageGetTagTree();

  Future<String> crateApiSimpleGreet({required String name});

  Future<String> crateApiStorageImportPdf({
    required String title,
    required String sourcePath,
    String? folderId,
  });

  Future<void> crateApiPdfInitPdfium({String? libraryPath});

  Future<void> crateApiStorageInitStorage({
    required String dbPath,
    required String sandboxDir,
  });

  Future<String> crateApiPdfLoadDocument({required String filePath});

  Future<void> crateApiStorageRemoveTagFromDocument({
    required String docId,
    required String tagId,
  });

  Future<void> crateApiStorageRenameFolder({
    required String id,
    required String newName,
  });

  Future<void> crateApiStorageRenameTag({
    required String id,
    required String newName,
  });

  Future<Uint8List> crateApiPdfRenderViewport({required ViewportRequest req});

  Future<void> crateApiStorageUpdateAnnotation({
    required String id,
    required Map<String, String> updates,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiStorageAddTagToDocument({
    required String docId,
    required String tagId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_String(tagId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageAddTagToDocumentConstMeta,
        argValues: [docId, tagId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageAddTagToDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "add_tag_to_document",
        argNames: ["docId", "tagId"],
      );

  @override
  Future<void> crateApiPdfCloseDocument({required String docId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfCloseDocumentConstMeta,
        argValues: [docId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfCloseDocumentConstMeta =>
      const TaskConstMeta(debugName: "close_document", argNames: ["docId"]);

  @override
  Future<String> crateApiStorageCreateAnnotation({
    required AnnotationRecord annotation,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_annotation_record(annotation, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageCreateAnnotationConstMeta,
        argValues: [annotation],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "create_annotation",
        argNames: ["annotation"],
      );

  @override
  Future<String> crateApiStorageCreateAnnotationAutoId({
    required String documentId,
    required int pageIndex,
    required String annotationType,
    required bool isStandard,
    required String colorHex,
    int? startCharIndex,
    int? endCharIndex,
    String? selectedText,
    String? rectsJson,
    String? strokesJson,
    String? noteContent,
    String? noteRectJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentId, serializer);
          sse_encode_i_32(pageIndex, serializer);
          sse_encode_String(annotationType, serializer);
          sse_encode_bool(isStandard, serializer);
          sse_encode_String(colorHex, serializer);
          sse_encode_opt_box_autoadd_i_32(startCharIndex, serializer);
          sse_encode_opt_box_autoadd_i_32(endCharIndex, serializer);
          sse_encode_opt_String(selectedText, serializer);
          sse_encode_opt_String(rectsJson, serializer);
          sse_encode_opt_String(strokesJson, serializer);
          sse_encode_opt_String(noteContent, serializer);
          sse_encode_opt_String(noteRectJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageCreateAnnotationAutoIdConstMeta,
        argValues: [
          documentId,
          pageIndex,
          annotationType,
          isStandard,
          colorHex,
          startCharIndex,
          endCharIndex,
          selectedText,
          rectsJson,
          strokesJson,
          noteContent,
          noteRectJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateAnnotationAutoIdConstMeta =>
      const TaskConstMeta(
        debugName: "create_annotation_auto_id",
        argNames: [
          "documentId",
          "pageIndex",
          "annotationType",
          "isStandard",
          "colorHex",
          "startCharIndex",
          "endCharIndex",
          "selectedText",
          "rectsJson",
          "strokesJson",
          "noteContent",
          "noteRectJson",
        ],
      );

  @override
  Future<String> crateApiStorageCreateFolder({
    required String name,
    String? parentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(parentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageCreateFolderConstMeta,
        argValues: [name, parentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateFolderConstMeta =>
      const TaskConstMeta(
        debugName: "create_folder",
        argNames: ["name", "parentId"],
      );

  @override
  Future<String> crateApiStorageCreateTag({
    required String name,
    String? parentId,
    String? colorHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(parentId, serializer);
          sse_encode_opt_String(colorHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageCreateTagConstMeta,
        argValues: [name, parentId, colorHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateTagConstMeta => const TaskConstMeta(
    debugName: "create_tag",
    argNames: ["name", "parentId", "colorHex"],
  );

  @override
  Future<void> crateApiStorageDeleteAnnotation({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteAnnotationConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteAnnotationConstMeta =>
      const TaskConstMeta(debugName: "delete_annotation", argNames: ["id"]);

  @override
  Future<void> crateApiStorageDeleteAnnotationsForDocument({
    required String documentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteAnnotationsForDocumentConstMeta,
        argValues: [documentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteAnnotationsForDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "delete_annotations_for_document",
        argNames: ["documentId"],
      );

  @override
  Future<void> crateApiStorageDeleteDocument({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteDocumentConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteDocumentConstMeta =>
      const TaskConstMeta(debugName: "delete_document", argNames: ["id"]);

  @override
  Future<void> crateApiStorageDeleteFolder({
    required String id,
    required bool deleteDocuments,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_bool(deleteDocuments, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteFolderConstMeta,
        argValues: [id, deleteDocuments],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteFolderConstMeta =>
      const TaskConstMeta(
        debugName: "delete_folder",
        argNames: ["id", "deleteDocuments"],
      );

  @override
  Future<void> crateApiStorageDeleteTag({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteTagConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteTagConstMeta =>
      const TaskConstMeta(debugName: "delete_tag", argNames: ["id"]);

  @override
  Future<void> crateApiPdfExportPdfWithAnnotations({
    required String sourcePath,
    required String outputPath,
    required List<AnnotationRecord> annotations,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_list_annotation_record(annotations, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfExportPdfWithAnnotationsConstMeta,
        argValues: [sourcePath, outputPath, annotations],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfExportPdfWithAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "export_pdf_with_annotations",
        argNames: ["sourcePath", "outputPath", "annotations"],
      );

  @override
  Future<List<AnnotationRecord>> crateApiStorageGetAnnotations({
    required String documentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_annotation_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageGetAnnotationsConstMeta,
        argValues: [documentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "get_annotations",
        argNames: ["documentId"],
      );

  @override
  Future<List<AnnotationRecord>> crateApiStorageGetAnnotationsForPage({
    required String documentId,
    required int pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentId, serializer);
          sse_encode_i_32(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_annotation_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageGetAnnotationsForPageConstMeta,
        argValues: [documentId, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetAnnotationsForPageConstMeta =>
      const TaskConstMeta(
        debugName: "get_annotations_for_page",
        argNames: ["documentId", "pageIndex"],
      );

  @override
  Future<List<DocumentInfo>> crateApiStorageGetDocuments({
    String? folderId,
    String? tagId,
    String? searchQuery,
    required String sortBy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(folderId, serializer);
          sse_encode_opt_String(tagId, serializer);
          sse_encode_opt_String(searchQuery, serializer);
          sse_encode_String(sortBy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_document_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageGetDocumentsConstMeta,
        argValues: [folderId, tagId, searchQuery, sortBy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetDocumentsConstMeta =>
      const TaskConstMeta(
        debugName: "get_documents",
        argNames: ["folderId", "tagId", "searchQuery", "sortBy"],
      );

  @override
  Future<FolderNode> crateApiStorageGetFolderTree() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageGetFolderTreeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetFolderTreeConstMeta =>
      const TaskConstMeta(debugName: "get_folder_tree", argNames: []);

  @override
  Future<List<CharInfo>> crateApiPdfGetPageChars({
    required String docId,
    required int pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_u_32(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_char_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfGetPageCharsConstMeta,
        argValues: [docId, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfGetPageCharsConstMeta => const TaskConstMeta(
    debugName: "get_page_chars",
    argNames: ["docId", "pageIndex"],
  );

  @override
  Future<int> crateApiPdfGetPageCount({required String docId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfGetPageCountConstMeta,
        argValues: [docId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfGetPageCountConstMeta =>
      const TaskConstMeta(debugName: "get_page_count", argNames: ["docId"]);

  @override
  Future<(double, double)> crateApiPdfGetPageSize({
    required String docId,
    required int pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_u_32(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_f_32_f_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfGetPageSizeConstMeta,
        argValues: [docId, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfGetPageSizeConstMeta => const TaskConstMeta(
    debugName: "get_page_size",
    argNames: ["docId", "pageIndex"],
  );

  @override
  Future<TagNode> crateApiStorageGetTagTree() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tag_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageGetTagTreeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetTagTreeConstMeta =>
      const TaskConstMeta(debugName: "get_tag_tree", argNames: []);

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<String> crateApiStorageImportPdf({
    required String title,
    required String sourcePath,
    String? folderId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(sourcePath, serializer);
          sse_encode_opt_String(folderId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageImportPdfConstMeta,
        argValues: [title, sourcePath, folderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageImportPdfConstMeta => const TaskConstMeta(
    debugName: "import_pdf",
    argNames: ["title", "sourcePath", "folderId"],
  );

  @override
  Future<void> crateApiPdfInitPdfium({String? libraryPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(libraryPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfInitPdfiumConstMeta,
        argValues: [libraryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfInitPdfiumConstMeta =>
      const TaskConstMeta(debugName: "init_pdfium", argNames: ["libraryPath"]);

  @override
  Future<void> crateApiStorageInitStorage({
    required String dbPath,
    required String sandboxDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(sandboxDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageInitStorageConstMeta,
        argValues: [dbPath, sandboxDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageInitStorageConstMeta => const TaskConstMeta(
    debugName: "init_storage",
    argNames: ["dbPath", "sandboxDir"],
  );

  @override
  Future<String> crateApiPdfLoadDocument({required String filePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfLoadDocumentConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfLoadDocumentConstMeta =>
      const TaskConstMeta(debugName: "load_document", argNames: ["filePath"]);

  @override
  Future<void> crateApiStorageRemoveTagFromDocument({
    required String docId,
    required String tagId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_String(tagId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageRemoveTagFromDocumentConstMeta,
        argValues: [docId, tagId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageRemoveTagFromDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "remove_tag_from_document",
        argNames: ["docId", "tagId"],
      );

  @override
  Future<void> crateApiStorageRenameFolder({
    required String id,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageRenameFolderConstMeta,
        argValues: [id, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageRenameFolderConstMeta =>
      const TaskConstMeta(
        debugName: "rename_folder",
        argNames: ["id", "newName"],
      );

  @override
  Future<void> crateApiStorageRenameTag({
    required String id,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageRenameTagConstMeta,
        argValues: [id, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageRenameTagConstMeta =>
      const TaskConstMeta(debugName: "rename_tag", argNames: ["id", "newName"]);

  @override
  Future<Uint8List> crateApiPdfRenderViewport({required ViewportRequest req}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_viewport_request(req, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfRenderViewportConstMeta,
        argValues: [req],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfRenderViewportConstMeta =>
      const TaskConstMeta(debugName: "render_viewport", argNames: ["req"]);

  @override
  Future<void> crateApiStorageUpdateAnnotation({
    required String id,
    required Map<String, String> updates,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_Map_String_String_None(updates, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageUpdateAnnotationConstMeta,
        argValues: [id, updates],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageUpdateAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "update_annotation",
        argNames: ["id", "updates"],
      );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnnotationRecord dco_decode_annotation_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return AnnotationRecord(
      id: dco_decode_String(arr[0]),
      documentId: dco_decode_String(arr[1]),
      pageIndex: dco_decode_i_32(arr[2]),
      annotationType: dco_decode_String(arr[3]),
      isStandard: dco_decode_bool(arr[4]),
      colorHex: dco_decode_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
      modifiedAt: dco_decode_i_64(arr[7]),
      startCharIndex: dco_decode_opt_box_autoadd_i_32(arr[8]),
      endCharIndex: dco_decode_opt_box_autoadd_i_32(arr[9]),
      selectedText: dco_decode_opt_String(arr[10]),
      rectsJson: dco_decode_opt_String(arr[11]),
      strokesJson: dco_decode_opt_String(arr[12]),
      noteContent: dco_decode_opt_String(arr[13]),
      noteRectJson: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AnnotationRecord dco_decode_box_autoadd_annotation_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_annotation_record(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ViewportRequest dco_decode_box_autoadd_viewport_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_viewport_request(raw);
  }

  @protected
  CharInfo dco_decode_char_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CharInfo(
      text: dco_decode_String(arr[0]),
      index: dco_decode_u_32(arr[1]),
      left: dco_decode_f_32(arr[2]),
      top: dco_decode_f_32(arr[3]),
      right: dco_decode_f_32(arr[4]),
      bottom: dco_decode_f_32(arr[5]),
    );
  }

  @protected
  DocumentInfo dco_decode_document_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DocumentInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      filePath: dco_decode_String(arr[2]),
      folderId: dco_decode_opt_String(arr[3]),
      tagIds: dco_decode_list_String(arr[4]),
      createdAt: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderNode dco_decode_folder_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FolderNode(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      children: dco_decode_list_folder_node(arr[2]),
      documentCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AnnotationRecord> dco_decode_list_annotation_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_annotation_record).toList();
  }

  @protected
  List<CharInfo> dco_decode_list_char_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_char_info).toList();
  }

  @protected
  List<DocumentInfo> dco_decode_list_document_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_document_info).toList();
  }

  @protected
  List<FolderNode> dco_decode_list_folder_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_folder_node).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<TagNode> dco_decode_list_tag_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag_node).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  (double, double) dco_decode_record_f_32_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_32(arr[0]), dco_decode_f_32(arr[1]));
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  TagNode dco_decode_tag_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TagNode(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      children: dco_decode_list_tag_node(arr[2]),
      colorHex: dco_decode_opt_String(arr[3]),
      documentCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ViewportRequest dco_decode_viewport_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ViewportRequest(
      docId: dco_decode_String(arr[0]),
      pageIndex: dco_decode_u_32(arr[1]),
      pdfLeft: dco_decode_f_32(arr[2]),
      pdfTop: dco_decode_f_32(arr[3]),
      pdfRight: dco_decode_f_32(arr[4]),
      pdfBottom: dco_decode_f_32(arr[5]),
      targetWidth: dco_decode_u_32(arr[6]),
      targetHeight: dco_decode_u_32(arr[7]),
      renderDpi: dco_decode_opt_box_autoadd_f_32(arr[8]),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnnotationRecord sse_decode_annotation_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_documentId = sse_decode_String(deserializer);
    var var_pageIndex = sse_decode_i_32(deserializer);
    var var_annotationType = sse_decode_String(deserializer);
    var var_isStandard = sse_decode_bool(deserializer);
    var var_colorHex = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_modifiedAt = sse_decode_i_64(deserializer);
    var var_startCharIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_endCharIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_selectedText = sse_decode_opt_String(deserializer);
    var var_rectsJson = sse_decode_opt_String(deserializer);
    var var_strokesJson = sse_decode_opt_String(deserializer);
    var var_noteContent = sse_decode_opt_String(deserializer);
    var var_noteRectJson = sse_decode_opt_String(deserializer);
    return AnnotationRecord(
      id: var_id,
      documentId: var_documentId,
      pageIndex: var_pageIndex,
      annotationType: var_annotationType,
      isStandard: var_isStandard,
      colorHex: var_colorHex,
      createdAt: var_createdAt,
      modifiedAt: var_modifiedAt,
      startCharIndex: var_startCharIndex,
      endCharIndex: var_endCharIndex,
      selectedText: var_selectedText,
      rectsJson: var_rectsJson,
      strokesJson: var_strokesJson,
      noteContent: var_noteContent,
      noteRectJson: var_noteRectJson,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AnnotationRecord sse_decode_box_autoadd_annotation_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_annotation_record(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  ViewportRequest sse_decode_box_autoadd_viewport_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_viewport_request(deserializer));
  }

  @protected
  CharInfo sse_decode_char_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_index = sse_decode_u_32(deserializer);
    var var_left = sse_decode_f_32(deserializer);
    var var_top = sse_decode_f_32(deserializer);
    var var_right = sse_decode_f_32(deserializer);
    var var_bottom = sse_decode_f_32(deserializer);
    return CharInfo(
      text: var_text,
      index: var_index,
      left: var_left,
      top: var_top,
      right: var_right,
      bottom: var_bottom,
    );
  }

  @protected
  DocumentInfo sse_decode_document_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_folderId = sse_decode_opt_String(deserializer);
    var var_tagIds = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return DocumentInfo(
      id: var_id,
      title: var_title,
      filePath: var_filePath,
      folderId: var_folderId,
      tagIds: var_tagIds,
      createdAt: var_createdAt,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FolderNode sse_decode_folder_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_children = sse_decode_list_folder_node(deserializer);
    var var_documentCount = sse_decode_u_32(deserializer);
    return FolderNode(
      id: var_id,
      name: var_name,
      children: var_children,
      documentCount: var_documentCount,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnnotationRecord> sse_decode_list_annotation_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnnotationRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_annotation_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<CharInfo> sse_decode_list_char_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CharInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_char_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<DocumentInfo> sse_decode_list_document_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DocumentInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_document_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<FolderNode> sse_decode_list_folder_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FolderNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_folder_node(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<TagNode> sse_decode_list_tag_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TagNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag_node(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double) sse_decode_record_f_32_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_32(deserializer);
    var var_field1 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TagNode sse_decode_tag_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_children = sse_decode_list_tag_node(deserializer);
    var var_colorHex = sse_decode_opt_String(deserializer);
    var var_documentCount = sse_decode_u_32(deserializer);
    return TagNode(
      id: var_id,
      name: var_name,
      children: var_children,
      colorHex: var_colorHex,
      documentCount: var_documentCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ViewportRequest sse_decode_viewport_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_docId = sse_decode_String(deserializer);
    var var_pageIndex = sse_decode_u_32(deserializer);
    var var_pdfLeft = sse_decode_f_32(deserializer);
    var var_pdfTop = sse_decode_f_32(deserializer);
    var var_pdfRight = sse_decode_f_32(deserializer);
    var var_pdfBottom = sse_decode_f_32(deserializer);
    var var_targetWidth = sse_decode_u_32(deserializer);
    var var_targetHeight = sse_decode_u_32(deserializer);
    var var_renderDpi = sse_decode_opt_box_autoadd_f_32(deserializer);
    return ViewportRequest(
      docId: var_docId,
      pageIndex: var_pageIndex,
      pdfLeft: var_pdfLeft,
      pdfTop: var_pdfTop,
      pdfRight: var_pdfRight,
      pdfBottom: var_pdfBottom,
      targetWidth: var_targetWidth,
      targetHeight: var_targetHeight,
      renderDpi: var_renderDpi,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_annotation_record(
    AnnotationRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.documentId, serializer);
    sse_encode_i_32(self.pageIndex, serializer);
    sse_encode_String(self.annotationType, serializer);
    sse_encode_bool(self.isStandard, serializer);
    sse_encode_String(self.colorHex, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.modifiedAt, serializer);
    sse_encode_opt_box_autoadd_i_32(self.startCharIndex, serializer);
    sse_encode_opt_box_autoadd_i_32(self.endCharIndex, serializer);
    sse_encode_opt_String(self.selectedText, serializer);
    sse_encode_opt_String(self.rectsJson, serializer);
    sse_encode_opt_String(self.strokesJson, serializer);
    sse_encode_opt_String(self.noteContent, serializer);
    sse_encode_opt_String(self.noteRectJson, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_annotation_record(
    AnnotationRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_annotation_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_viewport_request(self, serializer);
  }

  @protected
  void sse_encode_char_info(CharInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_u_32(self.index, serializer);
    sse_encode_f_32(self.left, serializer);
    sse_encode_f_32(self.top, serializer);
    sse_encode_f_32(self.right, serializer);
    sse_encode_f_32(self.bottom, serializer);
  }

  @protected
  void sse_encode_document_info(DocumentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_opt_String(self.folderId, serializer);
    sse_encode_list_String(self.tagIds, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_folder_node(FolderNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_folder_node(self.children, serializer);
    sse_encode_u_32(self.documentCount, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_annotation_record(
    List<AnnotationRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_annotation_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_char_info(
    List<CharInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_char_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_document_info(
    List<DocumentInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_document_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_folder_node(
    List<FolderNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_folder_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tag_node(List<TagNode> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag_node(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_32_f_32(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.$1, serializer);
    sse_encode_f_32(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_tag_node(TagNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_tag_node(self.children, serializer);
    sse_encode_opt_String(self.colorHex, serializer);
    sse_encode_u_32(self.documentCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.docId, serializer);
    sse_encode_u_32(self.pageIndex, serializer);
    sse_encode_f_32(self.pdfLeft, serializer);
    sse_encode_f_32(self.pdfTop, serializer);
    sse_encode_f_32(self.pdfRight, serializer);
    sse_encode_f_32(self.pdfBottom, serializer);
    sse_encode_u_32(self.targetWidth, serializer);
    sse_encode_u_32(self.targetHeight, serializer);
    sse_encode_opt_box_autoadd_f_32(self.renderDpi, serializer);
  }
}
