// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/pdf.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'storage/annotations.dart';
import 'storage/documents.dart';
import 'storage/folders.dart';
import 'storage/ink_layers.dart';
import 'storage/mindmap.dart';
import 'storage/tags.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnnotationRecord dco_decode_annotation_record(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnnotationRecord dco_decode_box_autoadd_annotation_record(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  InkLayerRecord dco_decode_box_autoadd_ink_layer_record(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  Topic dco_decode_box_autoadd_topic(dynamic raw);

  @protected
  ViewportRequest dco_decode_box_autoadd_viewport_request(dynamic raw);

  @protected
  CharInfo dco_decode_char_info(dynamic raw);

  @protected
  DocumentInfo dco_decode_document_info(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FolderNode dco_decode_folder_node(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InkLayerRecord dco_decode_ink_layer_record(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnnotationRecord> dco_decode_list_annotation_record(dynamic raw);

  @protected
  List<CharInfo> dco_decode_list_char_info(dynamic raw);

  @protected
  List<DocumentInfo> dco_decode_list_document_info(dynamic raw);

  @protected
  List<FolderNode> dco_decode_list_folder_node(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<TagNode> dco_decode_list_tag_node(dynamic raw);

  @protected
  List<Topic> dco_decode_list_topic(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  InkLayerRecord? dco_decode_opt_box_autoadd_ink_layer_record(dynamic raw);

  @protected
  Note? dco_decode_opt_box_autoadd_note(dynamic raw);

  @protected
  Topic? dco_decode_opt_box_autoadd_topic(dynamic raw);

  @protected
  (double, double) dco_decode_record_f_32_f_32(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  TagNode dco_decode_tag_node(dynamic raw);

  @protected
  Topic dco_decode_topic(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ViewportRequest dco_decode_viewport_request(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnnotationRecord sse_decode_annotation_record(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnnotationRecord sse_decode_box_autoadd_annotation_record(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InkLayerRecord sse_decode_box_autoadd_ink_layer_record(
    SseDeserializer deserializer,
  );

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  Topic sse_decode_box_autoadd_topic(SseDeserializer deserializer);

  @protected
  ViewportRequest sse_decode_box_autoadd_viewport_request(
    SseDeserializer deserializer,
  );

  @protected
  CharInfo sse_decode_char_info(SseDeserializer deserializer);

  @protected
  DocumentInfo sse_decode_document_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FolderNode sse_decode_folder_node(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InkLayerRecord sse_decode_ink_layer_record(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnnotationRecord> sse_decode_list_annotation_record(
    SseDeserializer deserializer,
  );

  @protected
  List<CharInfo> sse_decode_list_char_info(SseDeserializer deserializer);

  @protected
  List<DocumentInfo> sse_decode_list_document_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FolderNode> sse_decode_list_folder_node(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<TagNode> sse_decode_list_tag_node(SseDeserializer deserializer);

  @protected
  List<Topic> sse_decode_list_topic(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InkLayerRecord? sse_decode_opt_box_autoadd_ink_layer_record(
    SseDeserializer deserializer,
  );

  @protected
  Note? sse_decode_opt_box_autoadd_note(SseDeserializer deserializer);

  @protected
  Topic? sse_decode_opt_box_autoadd_topic(SseDeserializer deserializer);

  @protected
  (double, double) sse_decode_record_f_32_f_32(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  TagNode sse_decode_tag_node(SseDeserializer deserializer);

  @protected
  Topic sse_decode_topic(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ViewportRequest sse_decode_viewport_request(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_annotation_record(
    AnnotationRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_annotation_record(
    AnnotationRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ink_layer_record(
    InkLayerRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_topic(Topic self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_char_info(CharInfo self, SseSerializer serializer);

  @protected
  void sse_encode_document_info(DocumentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder_node(FolderNode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ink_layer_record(
    InkLayerRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_annotation_record(
    List<AnnotationRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_char_info(List<CharInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_info(
    List<DocumentInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_folder_node(
    List<FolderNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag_node(List<TagNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_topic(List<Topic> self, SseSerializer serializer);

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ink_layer_record(
    InkLayerRecord? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_note(Note? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_topic(Topic? self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_32_f_32(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag_node(TagNode self, SseSerializer serializer);

  @protected
  void sse_encode_topic(Topic self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
