// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Annotation record for database storage.
class AnnotationRecord {
  final String id;
  final String documentId;
  final int pageIndex;
  final String annotationType;
  final bool isStandard;
  final String colorHex;
  final PlatformInt64 createdAt;
  final PlatformInt64 modifiedAt;
  final int? startCharIndex;
  final int? endCharIndex;
  final String? selectedText;
  final String? rectsJson;
  final String? strokesJson;
  final String? noteContent;
  final String? noteRectJson;

  const AnnotationRecord({
    required this.id,
    required this.documentId,
    required this.pageIndex,
    required this.annotationType,
    required this.isStandard,
    required this.colorHex,
    required this.createdAt,
    required this.modifiedAt,
    this.startCharIndex,
    this.endCharIndex,
    this.selectedText,
    this.rectsJson,
    this.strokesJson,
    this.noteContent,
    this.noteRectJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      documentId.hashCode ^
      pageIndex.hashCode ^
      annotationType.hashCode ^
      isStandard.hashCode ^
      colorHex.hashCode ^
      createdAt.hashCode ^
      modifiedAt.hashCode ^
      startCharIndex.hashCode ^
      endCharIndex.hashCode ^
      selectedText.hashCode ^
      rectsJson.hashCode ^
      strokesJson.hashCode ^
      noteContent.hashCode ^
      noteRectJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnnotationRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          documentId == other.documentId &&
          pageIndex == other.pageIndex &&
          annotationType == other.annotationType &&
          isStandard == other.isStandard &&
          colorHex == other.colorHex &&
          createdAt == other.createdAt &&
          modifiedAt == other.modifiedAt &&
          startCharIndex == other.startCharIndex &&
          endCharIndex == other.endCharIndex &&
          selectedText == other.selectedText &&
          rectsJson == other.rectsJson &&
          strokesJson == other.strokesJson &&
          noteContent == other.noteContent &&
          noteRectJson == other.noteRectJson;
}
