// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DocumentInfo {
  final String id;
  final String title;
  final String filePath;
  final String? folderId;
  final List<String> tagIds;
  final PlatformInt64 createdAt;

  const DocumentInfo({
    required this.id,
    required this.title,
    required this.filePath,
    this.folderId,
    required this.tagIds,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      filePath.hashCode ^
      folderId.hashCode ^
      tagIds.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          filePath == other.filePath &&
          folderId == other.folderId &&
          tagIds == other.tagIds &&
          createdAt == other.createdAt;
}
