// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FolderNode {
  final String id;
  final String name;
  final List<FolderNode> children;
  final int documentCount;

  const FolderNode({
    required this.id,
    required this.name,
    required this.children,
    required this.documentCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ children.hashCode ^ documentCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          children == other.children &&
          documentCount == other.documentCount;
}
