// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InkLayerRecord {
  final String id;
  final String layerType;
  final String ownerId;
  final String strokesJson;
  final int zIndex;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const InkLayerRecord({
    required this.id,
    required this.layerType,
    required this.ownerId,
    required this.strokesJson,
    required this.zIndex,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      layerType.hashCode ^
      ownerId.hashCode ^
      strokesJson.hashCode ^
      zIndex.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InkLayerRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          layerType == other.layerType &&
          ownerId == other.ownerId &&
          strokesJson == other.strokesJson &&
          zIndex == other.zIndex &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
