// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Note (导图节点) 实体
class Note {
  final String id;
  final String topicId;
  final String? parentId;
  final String title;
  final String? contentJson;
  final String? childIds;
  final String? pdfId;
  final int? startPage;
  final int? endPage;
  final String? startPos;
  final String? endPos;
  final String? highlightText;
  final String? highlightStyle;
  final String? mediaIds;
  final double? positionX;
  final double? positionY;
  final int zIndex;
  final bool isCollapsed;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64 syncVersion;

  const Note({
    required this.id,
    required this.topicId,
    this.parentId,
    required this.title,
    this.contentJson,
    this.childIds,
    this.pdfId,
    this.startPage,
    this.endPage,
    this.startPos,
    this.endPos,
    this.highlightText,
    this.highlightStyle,
    this.mediaIds,
    this.positionX,
    this.positionY,
    required this.zIndex,
    required this.isCollapsed,
    required this.createdAt,
    required this.updatedAt,
    required this.syncVersion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      topicId.hashCode ^
      parentId.hashCode ^
      title.hashCode ^
      contentJson.hashCode ^
      childIds.hashCode ^
      pdfId.hashCode ^
      startPage.hashCode ^
      endPage.hashCode ^
      startPos.hashCode ^
      endPos.hashCode ^
      highlightText.hashCode ^
      highlightStyle.hashCode ^
      mediaIds.hashCode ^
      positionX.hashCode ^
      positionY.hashCode ^
      zIndex.hashCode ^
      isCollapsed.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      syncVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          topicId == other.topicId &&
          parentId == other.parentId &&
          title == other.title &&
          contentJson == other.contentJson &&
          childIds == other.childIds &&
          pdfId == other.pdfId &&
          startPage == other.startPage &&
          endPage == other.endPage &&
          startPos == other.startPos &&
          endPos == other.endPos &&
          highlightText == other.highlightText &&
          highlightStyle == other.highlightStyle &&
          mediaIds == other.mediaIds &&
          positionX == other.positionX &&
          positionY == other.positionY &&
          zIndex == other.zIndex &&
          isCollapsed == other.isCollapsed &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          syncVersion == other.syncVersion;
}

/// Topic (笔记本) 实体
class Topic {
  final String id;
  final String title;
  final String? author;
  final String? pdfIds;
  final String? rootNoteIds;
  final String? thumbnailPath;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? lastVisitAt;
  final bool isTrashed;
  final PlatformInt64 syncVersion;

  const Topic({
    required this.id,
    required this.title,
    this.author,
    this.pdfIds,
    this.rootNoteIds,
    this.thumbnailPath,
    required this.createdAt,
    required this.updatedAt,
    this.lastVisitAt,
    required this.isTrashed,
    required this.syncVersion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      pdfIds.hashCode ^
      rootNoteIds.hashCode ^
      thumbnailPath.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      lastVisitAt.hashCode ^
      isTrashed.hashCode ^
      syncVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Topic &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          pdfIds == other.pdfIds &&
          rootNoteIds == other.rootNoteIds &&
          thumbnailPath == other.thumbnailPath &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          lastVisitAt == other.lastVisitAt &&
          isTrashed == other.isTrashed &&
          syncVersion == other.syncVersion;
}
