// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TagNode {
  final String id;
  final String name;
  final List<TagNode> children;
  final String? colorHex;
  final int documentCount;

  const TagNode({
    required this.id,
    required this.name,
    required this.children,
    this.colorHex,
    required this.documentCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      children.hashCode ^
      colorHex.hashCode ^
      documentCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          children == other.children &&
          colorHex == other.colorHex &&
          documentCount == other.documentCount;
}
