// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../storage/annotations.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_standard_annotation`, `parse_color_hex`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FPDF_FS_RECTF`, `PdfDocumentWrapper`, `PdfiumWrapper`

Future<void> initPdfium({String? libraryPath}) =>
    RustLib.instance.api.crateApiPdfInitPdfium(libraryPath: libraryPath);

Future<String> loadDocument({required String filePath}) =>
    RustLib.instance.api.crateApiPdfLoadDocument(filePath: filePath);

Future<void> closeDocument({required String docId}) =>
    RustLib.instance.api.crateApiPdfCloseDocument(docId: docId);

Future<int> getPageCount({required String docId}) =>
    RustLib.instance.api.crateApiPdfGetPageCount(docId: docId);

Future<(double, double)> getPageSize({
  required String docId,
  required int pageIndex,
}) => RustLib.instance.api.crateApiPdfGetPageSize(
  docId: docId,
  pageIndex: pageIndex,
);

Future<Uint8List> renderViewport({required ViewportRequest req}) =>
    RustLib.instance.api.crateApiPdfRenderViewport(req: req);

Future<List<CharInfo>> getPageChars({
  required String docId,
  required int pageIndex,
}) => RustLib.instance.api.crateApiPdfGetPageChars(
  docId: docId,
  pageIndex: pageIndex,
);

/// Exports a PDF with annotations rendered into it.
///
/// Standard annotations (highlight, underline) are added as PDF native annotation objects.
/// Private annotations (wave, ink, note) are rendered as graphics on the page.
Future<void> exportPdfWithAnnotations({
  required String sourcePath,
  required String outputPath,
  required List<AnnotationRecord> annotations,
}) => RustLib.instance.api.crateApiPdfExportPdfWithAnnotations(
  sourcePath: sourcePath,
  outputPath: outputPath,
  annotations: annotations,
);

class CharInfo {
  final String text;
  final int index;
  final double left;
  final double top;
  final double right;
  final double bottom;

  const CharInfo({
    required this.text,
    required this.index,
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      index.hashCode ^
      left.hashCode ^
      top.hashCode ^
      right.hashCode ^
      bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharInfo &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          index == other.index &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}

class ViewportRequest {
  final String docId;
  final int pageIndex;
  final double pdfLeft;
  final double pdfTop;
  final double pdfRight;
  final double pdfBottom;
  final int targetWidth;
  final int targetHeight;
  final double? renderDpi;

  const ViewportRequest({
    required this.docId,
    required this.pageIndex,
    required this.pdfLeft,
    required this.pdfTop,
    required this.pdfRight,
    required this.pdfBottom,
    required this.targetWidth,
    required this.targetHeight,
    this.renderDpi,
  });

  @override
  int get hashCode =>
      docId.hashCode ^
      pageIndex.hashCode ^
      pdfLeft.hashCode ^
      pdfTop.hashCode ^
      pdfRight.hashCode ^
      pdfBottom.hashCode ^
      targetWidth.hashCode ^
      targetHeight.hashCode ^
      renderDpi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportRequest &&
          runtimeType == other.runtimeType &&
          docId == other.docId &&
          pageIndex == other.pageIndex &&
          pdfLeft == other.pdfLeft &&
          pdfTop == other.pdfTop &&
          pdfRight == other.pdfRight &&
          pdfBottom == other.pdfBottom &&
          targetWidth == other.targetWidth &&
          targetHeight == other.targetHeight &&
          renderDpi == other.renderDpi;
}
