// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../storage/annotations.dart';
import '../storage/documents.dart';
import '../storage/folders.dart';
import '../storage/tags.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initializes the database connection and logs the sandbox path.
Future<void> initStorage({
  required String dbPath,
  required String sandboxDir,
}) => RustLib.instance.api.crateApiStorageInitStorage(
  dbPath: dbPath,
  sandboxDir: sandboxDir,
);

/// Returns the complete hierarchical folder tree.
Future<FolderNode> getFolderTree() =>
    RustLib.instance.api.crateApiStorageGetFolderTree();

/// Creates a folder and returns its UUID.
Future<String> createFolder({required String name, String? parentId}) => RustLib
    .instance
    .api
    .crateApiStorageCreateFolder(name: name, parentId: parentId);

/// Renames a folder.
Future<void> renameFolder({required String id, required String newName}) =>
    RustLib.instance.api.crateApiStorageRenameFolder(id: id, newName: newName);

/// Deletes a folder. If `delete_documents` is true, deletes all documents inside this folder
/// and its subfolders, physically removing their PDF files.
Future<void> deleteFolder({
  required String id,
  required bool deleteDocuments,
}) => RustLib.instance.api.crateApiStorageDeleteFolder(
  id: id,
  deleteDocuments: deleteDocuments,
);

/// Returns the complete hierarchical tag tree.
Future<TagNode> getTagTree() =>
    RustLib.instance.api.crateApiStorageGetTagTree();

/// Creates a tag and returns its UUID.
Future<String> createTag({
  required String name,
  String? parentId,
  String? colorHex,
}) => RustLib.instance.api.crateApiStorageCreateTag(
  name: name,
  parentId: parentId,
  colorHex: colorHex,
);

/// Renames a tag.
Future<void> renameTag({required String id, required String newName}) =>
    RustLib.instance.api.crateApiStorageRenameTag(id: id, newName: newName);

/// Deletes a tag.
Future<void> deleteTag({required String id}) =>
    RustLib.instance.api.crateApiStorageDeleteTag(id: id);

/// Imports a PDF file, copying it into the sandboxed location.
Future<String> importPdf({
  required String title,
  required String sourcePath,
  String? folderId,
}) => RustLib.instance.api.crateApiStorageImportPdf(
  title: title,
  sourcePath: sourcePath,
  folderId: folderId,
);

/// Deletes a document record and removes its physical sandboxed file.
Future<void> deleteDocument({required String id}) =>
    RustLib.instance.api.crateApiStorageDeleteDocument(id: id);

/// Appends a tag to a document.
Future<void> addTagToDocument({required String docId, required String tagId}) =>
    RustLib.instance.api.crateApiStorageAddTagToDocument(
      docId: docId,
      tagId: tagId,
    );

/// Removes a tag from a document.
Future<void> removeTagFromDocument({
  required String docId,
  required String tagId,
}) => RustLib.instance.api.crateApiStorageRemoveTagFromDocument(
  docId: docId,
  tagId: tagId,
);

/// Returns filtered, queried, and sorted list of documents.
Future<List<DocumentInfo>> getDocuments({
  String? folderId,
  String? tagId,
  String? searchQuery,
  required String sortBy,
}) => RustLib.instance.api.crateApiStorageGetDocuments(
  folderId: folderId,
  tagId: tagId,
  searchQuery: searchQuery,
  sortBy: sortBy,
);

/// Creates a new annotation and returns its ID.
Future<String> createAnnotation({required AnnotationRecord annotation}) =>
    RustLib.instance.api.crateApiStorageCreateAnnotation(
      annotation: annotation,
    );

/// Creates a new annotation with auto-generated ID.
Future<String> createAnnotationAutoId({
  required String documentId,
  required int pageIndex,
  required String annotationType,
  required bool isStandard,
  required String colorHex,
  int? startCharIndex,
  int? endCharIndex,
  String? selectedText,
  String? rectsJson,
  String? strokesJson,
  String? noteContent,
  String? noteRectJson,
}) => RustLib.instance.api.crateApiStorageCreateAnnotationAutoId(
  documentId: documentId,
  pageIndex: pageIndex,
  annotationType: annotationType,
  isStandard: isStandard,
  colorHex: colorHex,
  startCharIndex: startCharIndex,
  endCharIndex: endCharIndex,
  selectedText: selectedText,
  rectsJson: rectsJson,
  strokesJson: strokesJson,
  noteContent: noteContent,
  noteRectJson: noteRectJson,
);

/// Gets all annotations for a document.
Future<List<AnnotationRecord>> getAnnotations({required String documentId}) =>
    RustLib.instance.api.crateApiStorageGetAnnotations(documentId: documentId);

/// Gets annotations for a specific page.
Future<List<AnnotationRecord>> getAnnotationsForPage({
  required String documentId,
  required int pageIndex,
}) => RustLib.instance.api.crateApiStorageGetAnnotationsForPage(
  documentId: documentId,
  pageIndex: pageIndex,
);

/// Updates an annotation.
Future<void> updateAnnotation({
  required String id,
  required Map<String, String> updates,
}) => RustLib.instance.api.crateApiStorageUpdateAnnotation(
  id: id,
  updates: updates,
);

/// Deletes an annotation.
Future<void> deleteAnnotation({required String id}) =>
    RustLib.instance.api.crateApiStorageDeleteAnnotation(id: id);

/// Deletes all annotations for a document.
Future<void> deleteAnnotationsForDocument({required String documentId}) =>
    RustLib.instance.api.crateApiStorageDeleteAnnotationsForDocument(
      documentId: documentId,
    );
